version: "3.9"

services:
  admin:
    container_name: flygoose-blog-admin
    image: flygoose-blog-admin:v1
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - ./.env
    restart: on-failure
    networks:
      - flygoose

networks:
  flygoose:
    driver: bridge