/** generated by vite-plugin-runtime */
interface ImportMetaEnv {
  readonly API_PREFIX: string;
  readonly API_BASE_URL: string;
  readonly API_BASE_UPLOAD_IMG_URL: string;
}
interface ImportMeta {
  readonly env: ImportMetaEnv;
}
